spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl?user=root
    username: root
    password: 1324
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        show_sql: true

logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: info